### ISSUE TITLE
Building on OSX 10.9

### ISSUE THREAD

**Issue by JCash** [emoon/ProDBG#50]
Just got around to try to build the project, and got stuck on the qt version(s).

I downloaded the Qt 5.2.0 version and set the QT5 env var to that folder (Qt/5.2.0/clang_64), which makes it find the bin folder, but unfortunately not the QtWidgets include. This is easy to understand since apparently, the installer for Qt5.2 stopped shipping all the includes(!?). The Qt5.1.0 installer contains all include folders, but then Qt won't build on OSX 10.9 (it seems to only support 10.8).

So I tried building the source from Qt/5.2.0/Src/qtbase, but running make install gave me the same missing include folders. I've reached the highest level of success by setting the QT5 to the Src/qtbase directory since the bin and includes are there. However, then I get a build error: 

qmetatype.h:2040:97: error: declaration requires an exit-time destructor [-Werror,-Wexit-time-destructors]
    QtMetaTypePrivate::QPairVariantInterfaceConvertFunctor<T> > f(o);

Any suggestions on how to "build from scratch" ? I propose adding these build notes to the readme for future readers.

Regards,
Mathias
